### ISSUE TITLE
Still building?

### ISSUE THREAD

**Issue by MaxBittker** [stackgl/packages#19]
I added a package to the wiki, and haven't seen a new commit to gh-pages. is there anything i can do to diagnose this or help fix?

**Comment by rreusser** [comment]
Did you run `deploy`? I think it requires manual rebuilding + deploying. See: https://github.com/stackgl/stackgl.github.io/issues/8

I've been meaning to add those for a loooong time… Please give me vigorous kick as needed to get this done.

**Comment by rreusser** [comment]
Okay, I've added them to `packages/wiki`. Now to figure out how to deploy…

**Comment by rreusser** [comment]
Trying to run `npm run sync` in `packages`, but I get:

```
Your GitHub username: rreusser
Your GitHub password: ✔

Your GitHub OTP/2FA Code (optional): ******
/Users/rreusser/node/stackgl/packages/build-sync.js:16
    if (err) throw err
             ^

Error: Not Found
  at Request._callback (/Users/rreusser/node/stackgl/packages/node_modules/ecosystem-docs/sync.js:139:37)
  at Request.self.callback (/Users/rreusser/node/stackgl/packages/node_modules/request/request.js:186:22)
  at emitTwo (events.js:126:13)
```

Which I think means `ghauth` is just returning `Error: Not Found`. Hmm…

**Comment by MaxBittker** [comment]
thanks @rreusser! 
http://stack.gl/packages/ <- this page alludes to some automated deploy process, any idea who was running that?

**Comment by MaxBittker** [comment]
I'd love to help get this running again, so much good stuff not synced! 
```
> packages@1.0.0 sync /Users/maxbittker/etc/packages
> node build-sync

/Users/maxbittker/etc/packages/node_modules/first-mate/lib/grammar-registry.js:107
        throw new Error("Grammar missing required scopeName property: " + grammarPath);
        ^

Error: Grammar missing required scopeName property: /Users/maxbittker/etc/packages/node_modules/language-javascript/grammars/tree-sitter-javascript.cson
  at GrammarRegistry.module.exports.GrammarRegistry.readGrammarSync (/Users/maxbittker/etc/packages/node_modules/first-mate/lib/grammar-registry.js:107:15)
  at GrammarRegistry.module.exports.GrammarRegistry.loadGrammarSync (/Users/maxbittker/etc/packages/node_modules/first-mate/lib/grammar-registry.js:133:22)
  at Highlights.module.exports.Highlights.requireGrammarsSync (/Users/maxbittker/etc/packages/node_modules/highlights/lib/highlights.js:95:25)
  at /Users/maxbittker/etc/packages/highlight.js:16:22
  at Array.forEach (<anonymous>:null:null)
  at Object.<anonymous> (/Users/maxbittker/etc/packages/highlight.js:15:24)
  at Module._compile (module.js:624:30)
  at Object.require.extensions.(anonymous function) [as .js] (/Users/maxbittker/etc/packages/node_modules/node-jsx/index.js:29:12)
  at Module.load (module.js:545:32)
  at tryModuleLoad (module.js:508:12)
  at Function.Module._load (module.js:500:3)
  at Module.require (module.js:568:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/maxbittker/etc/packages/build.js:3:20)
  at Module._compile (module.js:624:30)
  at Object.require.extensions.(anonymous function) [as .js] (/Users/maxbittker/etc/packages/node_modules/node-jsx/index.js:29:12)
  at Module.load (module.js:545:32)
  at tryModuleLoad (module.js:508:12)
  at Function.Module._load (module.js:500:3)
  at Module.require (module.js:568:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/maxbittker/etc/packages/build-sync.js:3:17)
  at Module._compile (module.js:624:30)
  at Object.Module._extensions..js (module.js:635:10)
  at Module.load (module.js:545:32)
  at tryModuleLoad (module.js:508:12)
  at Function.Module._load (module.js:500:3)
  at Function.Module.runMain (module.js:665:10)
  at startup (bootstrap_node.js:187:16)
  at bootstrap_node.js:608:3```

**Comment by MaxBittker** [comment]
this seems like package rot possibly? maybe i need to pin a dependency back?

**Comment by MaxBittker** [comment]
the offending package appears to be highlights

**Comment by kevzettler** [comment]
Hey this would be very helpful to get back in I just wasted a bunch of time reinventing a lot of `primitive-geometry` package that was not listed at http://stack.gl/packages/. but it was published to NPM and also already added to the wiki here

**Comment by kevzettler** [comment]
I was able to get `deploy` to run it looked successful but it didn't seem to do anything

```
kevs-mbp:packages kevzettler$ npm run deploy

> packages@1.0.0 predeploy /Users/kevzettler/code/packages
> browserify index.js | uglifyjs -cm > dist/bundle.js && cssnext -cU index.css dist/bundle.css

WARN: Side effects in initialization of unused variable path [-:68,4]
WARN: Side effects in initialization of unused variable path [-:243,4]
WARN: Dropping unused variable _i [-:399,62]
WARN: Dropping unused variable _ref [-:399,66]
WARN: Dropping unused variable _i [-:476,126]
WARN: Dropping unused variable _ref [-:476,130]

> packages@1.0.0 deploy /Users/kevzettler/code/packages
> gh-pages -d dist

Cloning git@github.com:stackgl/packages.git into node_modules/gh-pages/.cache
Cleaning
Fetching origin
Checking out origin/gh-pages
Removing files
Copying files
Adding all
Committing
Pushing
Published
```

**Comment by rreusser** [comment]
I don't think I ever figured out how to deploy, sorry.

**Comment by kevzettler** [comment]
Well I have fixed the build and can run a deploy manually. I tried to setup an automatic deploy action. The deploy action is failing because it is getting rate limited by github when executing requests to sync all the repos listed from the packages wiki. 
https://github.com/stackgl/packages/runs/577817974?check_suite_focus=true#step:5:214

This issue stems from within the `ecosystem-docs` module
https://github.com/hughsk/ecosystem-docs/blob/master/sync.js#L136-L139

The `ecosystem-docs` module is really stale. I'm not about to build out rate limit throttling logic on it. But maybe in the future.
